version: '3.9'

services:
  taxpayer:
    container_name: taxpayer
    image: taxpayer
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mysqlnet
    ports:
      - 5007:5007
    volumes:
      - ./:/app
    restart: always

  mysqldb-taxpayer:
    container_name: mysqldb-taxpayer
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: arsenalb2
      MYSQL_DATABASE: #####
      MYSQL_USER: #####
      MYSQL_PASSWORD: #####
    ports:
      - 3311:3306
    networks:
      - mysqlnet
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet: